###
GET http://localhost:9000/api/detalhes_course HTTP/1.1

###
POST http://localhost:9000/api/detalhes_course HTTP/1.1
Content-Type: application/json

{
    "nome":"Python",
    "duracao":"720 hrs",
    "detalhes":"curso python",
    "price": 1500,
    "image": "python.jpg"
    }


###
DELETE http://localhost:9000/api/detalhes_course/3 HTTP/1.1

###
PUT http://localhost:9000/api/detalhes_course/1 HTTP/1.1
Content-Type: application/json

{
    "price":3200

}


###
GET http://localhost:9000/api/estudantes HTTP/1.1

###
POST http://localhost:9000/api/estudantes HTTP/1.1
Content-Type: application/json

{
    "nome":"Milagros Zambrano",
    "usuario":"milagroz",
    "email":"milagrozambrano@gmail.com",
    "senha": "abctefm",
    "resenha":"abctefm",
    "image": "Milagro.jpg"
    }


###
DELETE http://localhost:9000/api/estudantes/4 HTTP/1.1

###
PUT http://localhost:9000/api/estudantes/2 HTTP/1.1
Content-Type: application/json

{
    "email":"miljyhap@gmail.com"

}


###
GET http://localhost:9000/api/professores HTTP/1.1

###
POST http://localhost:9000/api/professores HTTP/1.1
Content-Type: application/json

{
    "nome":"Carlos Loaiza",
    "usuario":"carlosl",
    "senha": "ptrtefg",
    "image": "Carlo.jpg",
     "id_courses":5
    }


###
DELETE http://localhost:9000/api/professores/4 HTTP/1.1

###
PUT http://localhost:9000/api/professores/3 HTTP/1.1
Content-Type: application/json

{
    "usuario":"moaizam"

}
