###
GET http://localhost:9000/api HTTP/1.1

###
POST http://localhost:9000/api HTTP/1.1
Content-Type: application/json

{
    "nome":"Maria Prieto",
    "email":"mariaprieto4@gmail.com",
    "phone":"(11)96239-1232",
    "endereco": "Estrada Galvao Bueno"
}

###
DELETE http://localhost:9000/api/3 HTTP/1.1

###
PUT http://localhost:9000/api/1 HTTP/1.1
Content-Type: application/json

{
    "phone": "(11)96779-1232"

}
